name: Docker Build
on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  checks:
    uses: ./.github/workflows/checks.yaml
  docker_build:
    needs: checks
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Image tag
        id: tag
        run: echo "value=commit_${GITHUB_SHA:0:7}" >> "$GITHUB_OUTPUT"
      - uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: hkgdevx/hosted-github-runner:${{ steps.tag.outputs.value }}
